# Generated by Django 3.2.9 on 2022-01-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0001_initial'),
        ('articles', '0004_article_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='Tags.Tag'),
        ),
    ]
