# Generated by Django 3.2.9 on 2022-01-13 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='수정날짜'),
            preserve_default=False,
        ),
    ]
