# Generated by Django 3.2.9 on 2022-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220113_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, help_text='gif/png/jpg 이미지를 업로드해주세요.', upload_to='accounts/avatar/%Y/%m/%d', verbose_name='프로필이미지'),
        ),
    ]
